"""Sphinx configuration for torch-tbccl. Build with `make docs` from the repository root."""
import re
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

project = "torch-tbccl"
author = "torch-tbccl contributors"
copyright = "torch-tbccl contributors"

_m = re.search(r'__version__\s*=\s*"([^"]+)"', (ROOT / "torch_tbccl/_version.py").read_text(), re.M)
release = _m.group(1) if _m else "unknown"
version = release

extensions = ["myst_parser", "sphinx_copybutton", "autoapi.extension"]
root_doc = "index"
source_suffix = {".md": "markdown", ".rst": "restructuredtext"}

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

myst_enable_extensions = ["colon_fence", "deflist"]
myst_heading_anchors = 3

html_theme = "furo"
html_title = f"torch-tbccl {release}"
html_static_path = []

# The API reference is generated by parsing the sources statically. The package is never imported, so
# building the documentation does not load PyTorch, GPU runtimes, native extensions or any peer.
autoapi_type = "python"
autoapi_dirs = ["../torch_tbccl"]
autoapi_root = "autoapi"
autoapi_add_toctree_entry = False
autoapi_keep_files = False
# Private modules are not part of the public API.
autoapi_ignore = ["*/_[a-z]*.py", "*/info.py"]
autoapi_options = ["members", "show-inheritance", "show-module-summary"]

# Imports of compiled extension modules cannot be resolved statically; that is expected here.
suppress_warnings = ["autoapi.python_import_resolution"]
